# sops.yaml
creation_rules:
  - gcp_kms: projects/bustling-vim-441514-g9/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/my-key
    # Specify any file patterns you want to auto-encrypt
    path_regex: '.*\.yaml$'
    encrypted_regex: '^(data)$'