
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-pgdb
  labels:
    name: namespace-pgdb

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-pgdb
  namespace: namespace-pgdb
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "mydb"

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-pgdb
  namespace: namespace-pgdb
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pgdb
  namespace: namespace-pgdb
  labels:
    app: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        env: dev
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: configmap-pgdb
        - secretRef:
            name: secret-pgdb

---

apiVersion: v1
kind: Service
metadata:
  name: service-pgdb
  namespace: namespace-pgdb
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
      - port: 5432
        targetPort: 5432
